function psf_emitor_comun(Rb1,Rb2,Rc,Re,beta,Vcc,A,f)

figure('Name','Schema',...
    'Units','normalized',...
    'Position',[0.05 0.1 0.7 0.8],...x
    'NumberTitle','off');
C = imread('C:\Users\drago\Desktop\Bratfalean Dragos GAC proiect\emitorcomun.png');
image(C);
axis off;

Vth=(Rb2./(Rb1+Rb2))*Vcc;
Rth=(Rb1*Rb2)/(Rb1+Rb2);

Ib=(Vth-0.7)./(Rth+(beta+1)*Re);
Ic=beta*Ib;
Ie=(beta+1).*Ib;
VCE=Vcc-Ic*Rc-Ie*Re;


fig=figure('Name','PSF+Smallsignal',...
    'Units','normalized',...
    'Position',[0.05 0.1 0.7 0.8],...
    'NumberTitle','off');
set(fig,'color','#4DBEEE');

bb=uibuttongroup('Visible','on',...
'BackgroundColor','g',...
'ForegroundColor','black',...
'Title','Q point',...
'FontSize',10,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.01 0.5 0.48 0.49]);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.1 0.9 0.1 0.06], ...
    'String','Rb1= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.1 0.6 0.1 0.06], ...
    'String','Rb2= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.4 0.9 0.1 0.06], ...
    'String','Rc= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.4 0.6 0.1 0.06], ...
    'String','Re= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.7 0.6 0.1 0.06], ...
    'String','Vcc= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.7 0.9 0.13 0.06], ...
    'String','Ib= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.1 0.3 0.1 0.06], ...
    'String','Ic= ','Parent',bb);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.7 0.3 0.1 0.06], ...
    'String','Vth= ','Parent',bb);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.4 0.3 0.1 0.06], ...
    'String','Rth=','Parent',bb);

uicontrol('Style','edit',...
    'Units','normalized',...
    'backgroundcolor',[1,1,1],...
    'Position',[0.2 0.9 0.1 0.06],...
    'String',Rb1,...
    'Callback','Rb1=str2num(get(gcbo,''String''))','Parent',bb);

uicontrol('Style','edit',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.2 0.6 0.1 0.06],...
    'String',Rb2,...
    'Callback','Rb2=str2num(get(gco,''String''))','Parent',bb);
uicontrol('Style','edit',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.5 0.9 0.1 0.06],...
    'String',Rc,...
    'Callback','Rc=str2num(get(gco,''String''))','Parent',bb);
uicontrol('Style','edit',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.5 0.6 0.1 0.06],...
    'String',Re,...
    'Callback','Re=str2num(get(gco,''String''))','Parent',bb);
uicontrol('Style','edit',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.8 0.6 0.1 0.06],...
    'String',Vcc,...
    'Callback','Vcc=str2num(get(gco,''String''))','Parent',bb);
uicontrol('Style','text',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.8 0.9 0.13 0.07],...
    'String',Ib,'Parent',bb);
uicontrol('Style','text',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.2 0.3 0.13 0.06],...
    'String',Ic,'Parent',bb);
uicontrol('Style','text',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.8 0.3 0.1 0.06],...
    'String',Vth,'Parent',bb);
uicontrol('Style','text',...
    'Units','normalized',...
    'backgroundcolor',[1 1 1],...
    'Position',[0.5 0.3 0.1 0.06],...
    'String',Rth,'Parent',bb);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.1 0.1 0.1 0.06], ...
    'String','VCE= ','Parent',bb);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.2 0.1 0.1 0.06], ...
    'String',VCE,'Parent',bb);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.38 0.1 0.2 0.08], ...
    'String','Amplitudinea semnalului de intrare=','Parent',bb);
uicontrol('Style','edit', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.57 0.1 0.1 0.08], ...
    'String',A,'Callback','A=str2num(get(gcbo,''String''))','Parent',bb);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.7 0.1 0.1 0.06], ...
    'String','f=','Parent',bb);
uicontrol('Style','edit', ...
    'Units','normalized', ...
    'backgroundcolor',[1 1 1],...
    'Position',[0.8 0.1 0.1 0.06], ...
    'String',f,'Callback','f=str2num(get(gco,''String''))','Parent',bb);

 uicontrol('Style','pushbutton',... % buton de reset
 'Units','normalized',...
 'Position',[0.47 0.35 0.08 .05],...
 'backgroundcolor','y',...
 'string','Calculeaza',...
 'Callback','close;psf_emitor_comun(Rb1,Rb2,Rc,Re,beta,Vcc,A,f)');

if(Ib<=0)
    close;
    msgbox("cut off region!!");
    else if(VCE==0)
        close;
        msgbox("saturation region!!");
   
    else
      
     subplot('Position',[0.05,0.05,0.4,0.4]);
%-----------------------------------------
% Date ridicate experimental
% Tranzistor Caracteristici de iesire
u_ce=[0 0.1 0.3 0.5 2.00 4.50 7.00 10.00 12.00 15.00 20.00]; % V
%-------------------------
ib_1=Ib; 
ic=[0 0.10 2 Ic*10^4-0.8 Ic*10^4-0.65 Ic*10^4-0.5 Ic*10^4-0.4 Ic*10^4-0.3 Ic*10^4-0.2 Ic*10^4-0.1 Ic*10^4].*10.^(-4); % mA
ib_2=2*Ib 
ic_b=[0 0.10 2 16 2*Ib*10^6-0.6 2*Ib*10^6-0.5 2*Ib*10^6-0.4 2*Ib*10^6-0.3 2*Ib*10^6-0.2 2*Ib*10^6-0.1 2*Ib*10^6].*10.^(-4); % mA
%-----------------------------------
% Reprezentarea grafica a punctelor ridicate experimental
plot(u_ce,ic,'ko');grid on; hold on;
plot(u_ce,ic_b,'bo');grid on; hold on;

% Reprezentarea grafica a caracteristicii
plot(u_ce,ic,'r');
plot(u_ce,ic_b,'g');
% Interpolare
pas=(max(u_ce)-min(u_ce))./200;
u_cef=min(u_ce):pas:max(u_ce);
icf=interp1(u_ce,ic,u_cef,'linear');
plot(u_cef,icf,'b');hold on;

%----------------------------
% Punctul static de functionare
u_ce0=VCE;
ic0=interp1(u_ce',ic',u_ce0),
plot(u_ce0,ic0,'rx','MarkerSize',16);
plot([u_ce0,u_ce0,0],[0,ic0,ic0],'r:');
%----------------------------------
xlabel(['Uce',' Uce0 =',num2str(u_ce0),'[ V ]']);
ylabel(['Ic',' Ic0 =',num2str(ic0),'[ A ]']);
title('Tranzistor Caracteristicile de iesire');
hold off;
%---------------------------------------
small_signal(beta,Rc,Rb1,Rb2,Re,Vcc,VCE,Ic,A,f);
    end
end
   
end





